import torch

from . import testing  # noqa: F401
from .fused import *  # noqa: F403
from .ops import *  # noqa: F403

__version__ = "2.1"

aten_lib = torch.library.Library("aten", "IMPL")


def enable(lib=aten_lib):
    lib.impl("abs", abs, "XPU")
    lib.impl("add.Tensor", add, "XPU")
    lib.impl("addmm", addmm, "XPU")
    lib.impl("arange.start_step", arange_start, "XPU")
    lib.impl("arange.start", arange_start, "XPU")
    lib.impl("arange", arange, "XPU")
    lib.impl("bitwise_and.Tensor", bitwise_and_tensor, "XPU")
    lib.impl("bitwise_and.Scalar", bitwise_and_scalar, "XPU")
    lib.impl("bitwise_and.Scalar_Tensor", bitwise_and_scalar_tensor, "XPU")
    lib.impl("bitwise_not", bitwise_not, "XPU")
    lib.impl("bitwise_or.Tensor", bitwise_or_tensor, "XPU")
    lib.impl("bitwise_or.Scalar", bitwise_or_scalar, "XPU")
    lib.impl("bitwise_or.Scalar_Tensor", bitwise_or_scalar_tensor, "XPU")
    lib.impl("bmm", bmm, "XPU")
    lib.impl("clamp", clamp, "XPU")
    lib.impl("clamp.Tensor", clamp_tensor, "XPU")
    lib.impl("cos", cos, "XPU")
    lib.impl("pad", pad, "XPU")
    lib.impl("cumsum", cumsum, "XPU")
    lib.impl("div.Tensor", true_divide, "XPU")
    lib.impl("div.Scalar", true_divide, "XPU")
    lib.impl("div.Tensor_mode", div_mode, "XPU")
    lib.impl("div.Scalar_mode", div_mode, "XPU")
    lib.impl("divide.Tensor", true_divide, "XPU")  # divide, an alias for div
    lib.impl("divide.Scalar", true_divide, "XPU")
    lib.impl("divide.Tensor_mode", div_mode, "XPU")
    lib.impl("divide.Scalar_mode", div_mode, "XPU")
    lib.impl("true_divide.Tensor", true_divide, "XPU")  # true_divide, an alias for div
    lib.impl("true_divide.Scalar", true_divide, "XPU")
    lib.impl("floor_divide", floor_divide, "XPU")
    lib.impl("floor_divide.Scalar", floor_divide, "XPU")
    lib.impl("remainder.Tensor", remainder, "XPU")
    lib.impl("native_dropout", native_dropout, "AutogradXPU")
    lib.impl("erf", erf, "XPU")
    lib.impl("embedding", embedding, "AutogradXPU")
    lib.impl("eq.Tensor", eq, "XPU")
    lib.impl("eq.Scalar", eq_scalar, "XPU")
    lib.impl("exp", exp, "XPU")
    lib.impl("exponential_", exponential_, "XPU")
    lib.impl("ge.Tensor", ge, "XPU")
    lib.impl("ge.Scalar", ge_scalar, "XPU")
    lib.impl("gelu", gelu, "AutogradXPU")
    lib.impl("native_group_norm", group_norm, "AutogradXPU")
    lib.impl("_weight_norm_interface", weight_norm, "AutogradXPU")
    lib.impl("gt.Tensor", gt, "XPU")
    lib.impl("gt.Scalar", gt_scalar, "XPU")
    lib.impl("isfinite", isfinite, "XPU")
    lib.impl("isin.Tensor_Tensor", isin, "XPU")
    lib.impl("isin.Scalar_Tensor", isin, "XPU")
    lib.impl("isin.Tensor_Scalar", isin, "XPU")
    lib.impl("isinf", isinf, "XPU")
    lib.impl("isnan", isnan, "XPU")
    lib.impl("minimum", minimum, "XPU")
    lib.impl("maximum", maximum, "XPU")
    lib.impl("native_layer_norm", layer_norm, "AutogradXPU")
    lib.impl("le.Tensor", le, "XPU")
    lib.impl("le.Scalar", le_scalar, "XPU")
    lib.impl("lt.Tensor", lt, "XPU")
    lib.impl("lt.Scalar", lt_scalar, "XPU")
    lib.impl("rms_norm", rms_norm, "XPU")
    lib.impl("rand", rand, "XPU")
    lib.impl("randn", randn, "XPU")
    lib.impl("rand_like", rand_like, "XPU")
    lib.impl("randn_like", randn_like, "XPU")
    lib.impl("zeros", zeros, "XPU")
    lib.impl("ones", ones, "XPU")
    lib.impl("full", full, "XPU")
    lib.impl("zeros_like", zeros_like, "XPU")
    lib.impl("ones_like", ones_like, "XPU")
    lib.impl("full_like", full_like, "XPU")
    lib.impl("resolve_neg", resolve_neg, "XPU")
    lib.impl("resolve_conj", resolve_conj, "XPU")
    lib.impl("normal.Tensor_float", normal_tensor_float, "XPU")
    lib.impl("normal.float_Tensor", normal_float_tensor, "XPU")
    lib.impl("normal.Tensor_Tensor", normal_tensor_tensor, "XPU")
    lib.impl("normal.float_float", normal_float_float, "XPU")
    lib.impl("uniform_", uniform_, "XPU")
    lib.impl("mean", mean, "XPU")
    lib.impl("mean.dim", mean_dim, "XPU")
    lib.impl("mm", mm, "XPU")
    lib.impl("mul.Tensor", mul, "XPU")
    lib.impl("multinomial", multinomial, "XPU")
    lib.impl("mv", mv, "XPU")
    lib.impl("ne.Tensor", ne, "XPU")
    lib.impl("ne.Scalar", ne_scalar, "XPU")
    lib.impl("neg", neg, "XPU")
    lib.impl("pow.Scalar", pow_scalar, "XPU")
    lib.impl("pow.Tensor_Scalar", pow_tensor_scalar, "XPU")
    lib.impl("pow.Tensor_Tensor", pow_tensor_tensor, "XPU")
    lib.impl("reciprocal", reciprocal, "XPU")
    lib.impl("relu", relu, "AutogradXPU")
    lib.impl("rsqrt", rsqrt, "XPU")
    lib.impl("sigmoid", sigmoid, "AutogradXPU")
    lib.impl("silu", silu, "AutogradXPU")
    lib.impl("sin", sin, "XPU")
    lib.impl("softmax.int", softmax, "AutogradXPU")
    lib.impl("sub.Tensor", sub, "XPU")
    lib.impl("tanh", tanh, "AutogradXPU")
    lib.impl("triu", triu, "XPU")
    lib.impl("topk", topk, "XPU")
    lib.impl("var_mean.correction", var_mean, "XPU")
    lib.impl("linalg_vector_norm", vector_norm, "XPU")
    lib.impl("where.self", where_self, "XPU")
    lib.impl("where.ScalarSelf", where_scalar_self, "XPU")
    lib.impl("where.ScalarOther", where_scalar_other, "XPU")
    lib.impl("max", max, "XPU")
    lib.impl("max.dim", max_dim, "XPU")
    lib.impl("min", min, "XPU")
    lib.impl("min.dim", min_dim, "XPU")
    lib.impl("amax", amax, "XPU")
    lib.impl("argmax", argmax, "XPU")
    lib.impl("prod", prod, "XPU")
    lib.impl("prod.dim_int", prod_dim, "XPU")
    lib.impl("sum", sum, "XPU")
    lib.impl("sum.dim_IntList", sum_dim, "XPU")
    lib.impl("all", all, "XPU")
    lib.impl("all.dim", all_dim, "XPU")
    lib.impl("all.dims", all_dims, "XPU")
    lib.impl("any", any, "XPU")
    lib.impl("any.dim", any_dim, "XPU")
    lib.impl("any.dims", any_dims, "XPU")
    lib.impl("log_softmax.int", log_softmax, "AutogradXPU")
    lib.impl("outer", outer, "AutogradXPU")
    lib.impl("cross_entropy_loss", cross_entropy_loss, "AutogradXPU")
    # lib.impl("scatter.src", scatter_src, "XPU")
    # lib.impl("scatter.reduce", scatter_reduce, "XPU")
    # lib.impl("gather", gather, "XPU")
    # lib.impl("gather.out", gather_out, "XPU")
    lib.impl("isclose", isclose, "XPU")
    lib.impl("allclose", allclose, "XPU")
    lib.impl("fill.Scalar", fill_scalar, "XPU")
    lib.impl("fill.Tensor", fill_tensor, "XPU")
    lib.impl("flip", flip, "XPU")
    lib.impl("tile", tile, "XPU")
    lib.impl("index_select", index_select, "XPU")
    lib.impl("masked_fill", masked_fill, "XPU")
    lib.impl("_unique2", _unique2, "XPU")
    lib.impl("nonzero", nonzero, "XPU")
    lib.impl("repeat", repeat, "XPU")
    lib.impl("masked_select", masked_select, "XPU")
    lib.impl("stack", stack, "XPU")
    lib.impl("hstack", hstack, "XPU")
    lib.impl("cat", cat, "XPU")
    lib.impl("repeat_interleave.self_int", repeat_interleave_self_int, "XPU")
    lib.impl("vstack", vstack, "XPU")
    lib.impl("repeat_interleave.Tensor", repeat_interleave_tensor, "XPU")


class use_gems:
    def __init__(self):
        self.lib = torch.library.Library("aten", "IMPL")

    def __enter__(self):
        enable(self.lib)

    def __exit__(self, exc_type, exc_val, exc_tb):
        del self.lib


__all__ = [
    "enable",
    "use_gems",
]
